---
title: "Lab 4"
author: "Summer Heschong"
date: "2025-02-05"
output: pdf_document
---
#setup
```{r setup, include=FALSE}
library(here)
library(tidyverse)

weather_data <- read_csv(here('Data/Raw/arc_weather.csv'))
str(weather_data)
```
#Tidy Functions
```{r New Tidy Functions}
#rename columns
weather_data <- weather_data %>%
  rename(daily_precip_mm = daily_precip)

#case_when
#create new column to indicate snowy days
weather_data <- weather_data %>%
#when the air temperature is below freezing
mutate(snow_days = case_when(mean_airtemp < 0 &
#and there is precipitation, we classify the day as SNOWY
                               daily_precip_mm > 0 ~ 'SNOW',
#alternatively, for all other cases, there's no snow
                            TRUE ~ 'NO SNOW'))

  
```

#Confidence Intervals
```{r Two-sided hypothesis test}
#save output of t.test() to new variable name
precip_test <- t.test(weather_data$daily_precip_mm,
                      conf.level = 0.90)
#examine the result
precip_test
```

```{r CIs for binary data}
#save output of binom.test() to new variable name.
vote_test <- binom.test(x = 187, n = 254,
                        conf.level = 0.90)
vote_test
```
#One-Sample Hypothesis Tests
```{r One Sample t-test}
#null hypothesis: the mean daily precipitation is 2mm
#alternative hypothesis: the mean daily precipitation is not 2 mm

#one-sample t-test
precip_ttest1 <- t.test(weather_data$daily_precip_mm,
                        mu = 2,
                        conf.level = 0.99,
                        alternative = 'two.sided')
precip_ttest1

#99% CI means alpha = 0.01

#p < 2.2e-16 so p < alpha

#we choose to reject the null hypothesis and retain the alternative
#hypothesis that mean daily precipitation is not 2 mm per day,
#because p < 0.01
```

```{r one-sided hypothesis test}
#null hypoth: the mean daily precipitation is less than 1mm
#alternative hypoth: the mean daily precip is greater than 1mm

#one sample t-test
precip_ttest2 <- t.test(weather_data$daily_precip_mm,
                        mu = 1,
                        conf.level = 0.99,
                        alternative = 'greater')
precip_ttest2

#99% CI means alpha = 0.01

#p = 0.9678 so p > alpha

#we choose to retain the null hypothesis that mean daily precip
#is less than 1mm per day, because p > 0.01.
```
#Two-Sample Hypothesis Test
```{r two sample t-test}
#first use case_when function to create a new column that categorizes
#records based on when they were collected
weather_data <- weather_data %>%
  mutate(time_period = case_when(date < '2003-01-01' ~ 'early',
                                 date >= '2003-01-01' ~ "late",
                                 TRUE ~ NA))
#we added the TRUE ~ NA athe the end in order to spit out an NA for 
#any row that does not adhere to any of the logical statements we've provided.

#Create an 'early' dataset using the filter function
early_data <- weather_data %>%
  filter(time_period == 'early')

#create a late dataset
late_data <- weather_data %>%
  filter(time_period == 'late')

#first test for equal variances
precip_vartest <- var.test(x = early_data$daily_precip_mm,
                           y = late_data$daily_precip_mm,
                           alternative = 'two.sided',
                           conf.level = 0.95)
precip_vartest

#p < 0.05 so we reject the null hypoth and retain the alternative hypot that the variances are not equal

#perform t-test calling data from new datasets. are the mean daly precips different from before and after 2003?
precip_ttest3 <- t.test(early_data$daily_precip_mm,
                        late_data$daily_precip_mm)
#r assumes the difference in means is 0 (mu = 0), and conf.level = 0.95 and we are interested in a two-sided, two-sample test.
precip_ttest3
```