---
title: "Week2_Lab_Assignment"
author: "Summer Heschong"
date: "2025-01-24"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---
#Setup: load packages and data
```{r setup}
library(here)
library(tidyverse)
library(viridis)
library(dplyr)

crab_data <- read.csv(here('Data/Raw/pie_crab.csv'))
```

#Part 1: Measures of location and data spread
```{r, Measures of location and data spread}
#a. What is the mean fiddler crab carapace size?

mean(crab_data$size)
#The mean fiddler crab carapace size is 14.66

#b. What is the median fiddler crab carapace size?

median(crab_data$size)
#The median fiddler crab carapace size is 14.44

#c. What is the standard deviation in fiddler crab carapace size? 

sd(crab_data$size)
#The standard deviation in fiddler crab carapace size is 3.5
```

#Part 2: Creating Histograms
```{r, Creating Histograms}
#a. Create histogram of fiddler crab carapace size
ggplot(data = crab_data, aes(x = size)) +
  geom_histogram(bins = 261, binwidth = 0.064) +
  labs(caption = 'Histogram of fiddler crab carapace size across sites')

#To find the right number of bins I used 2n^1/3 or 2(392)^1/3, and for bin width I used range/#of bins

#b. Create histograms of fiddler crab carapace size for each of the 13 sites
ggplot(data = crab_data, aes(x = size)) +
  geom_histogram(bins=20, binwidth = 0.25) +
  facet_wrap(~site)
  labs(caption = 'Histograms of fiddler crab carapace size by site')
  
```
c. How do the raw values of fiddler crab carapace size in your first figure compare to the mean and median values you calculated above? Based on your second figure, do any sites display strong diﬀerences in their data distributions?

Answer: 


```{r, Data Visualization}


```


